name: Testing
on: [push]
jobs:
    Testing:
        name: Initialize the code base
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.1
              with:
                  version: 'latest'

            - run: pnpm install
            - name: Legacy code base unit testing
              run: pnpm nx run-many --target=test --all
