name: Testing
on: [push]
jobs:
    Testing:
        name: Initialize the code base
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '12'
            - run: yarn
            - name: Legacy code base unit testing
              working-directory: ./packages/legacy
              run: yarn test
